name: Accept and Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
