name: Auto Pull Request

on:
  push:
    branches-ignore: 
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # Usa un PAT con scope 'repo'
          base: main                      # Rama destino del PR
          title: "Cambios desde ${{ github.ref_name }}"
          body: "Pull request automático para mergear cambios desde ${{ github.ref_name }}"
          labels: "automatic-pr"
